config/routes.rb
Rails.application.routes.draw do

  get 'pages/send_email'
  post 'pages/send_email'
  get 'pages/eng'
  root 'pages#index'

  namespace :admin do
    root 'application#admin'
    resources :wines
    resources :events
    resources :availabilities
  end

end

app/models/availability.rb
class Availability < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base

  CATEGORIES = [
        { name: 'Aktualitások'},
        { name: 'Események'}
    ]

  def is_facebook?
    url.downcase.include? 'facebook'
  end
end

app/models/wine.rb
class Wine < ActiveRecord::Base

  CATEGORIES = [
        { name: '1014 sorozat' },
        { name: 'Túrajeles sorozat' },
        { name: 'Borkülönlegességek' }
  ]
end

app/controllers/admin/application_controller.rb
# encoding: utf-8
class Admin::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_authentication

  layout 'admin'

  def admin
  end

  private
  def check_authentication
    authenticate_or_request_with_http_basic do |user, password|
      user == 'DubiczAdmin' && password == 'B0rpal0ta'
    end
  end
end

app/controllers/admin/availabilities_controller.rb
module Admin
class AvailabilitiesController < Admin::ApplicationController
  before_action :set_availability, only: [:show, :edit, :update, :destroy]

  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to admin_availability_path(@availability), notice: 'Availability was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to admin_availability_path(@availability), notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to admin_availabilities_path, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:name, :url)
    end
end
end

app/controllers/admin/events_controller.rb
module Admin
class EventsController < Admin::ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @event] }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:image, :name, :name_eng, :date_and_location, :date_and_location_eng, :start_date, :url_text, :url, :category)
    end
end
end

app/controllers/admin/wines_controller.rb
module Admin
class WinesController < Admin::ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to [:admin, @wine], notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @wine] }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to [:admin, @wine], notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @wine] }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to admin_wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:image, :kind, :kind_eng, :alcohol, :name, :name_eng, :year, :description, :description_eng, :category, :position)
    end
end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'application'

  before_action :authenticate unless Rails.env.development? || HOSTNAME == 'http://www.dubicz.hu'
  before_action :redirect_to_dubicz

  def index
  end

  def send_email
    UserMessage.user_message(params[:message]).deliver_now unless params[:message][:subject].present?
    redirect_to root_path
  end

  def eng
  end

  protected

  USERS = { 'DubiczAdmin' => 'B0rpal0ta'}
  def authenticate
    authenticate_or_request_with_http_digest do |name|
      USERS[name]
    end
  end

  def redirect_to_dubicz
    redirect_to "#{request.protocol}www.dubicz.hu#{request.fullpath}", :status => :moved_permanently unless request.host.in? %w(localhost www.dubicz.hu borpalota-staging.herokuapp.com)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/wines_helper.rb
module Admin::WinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/admin/application/admin.html.slim
.container
  h1 Admin

  .row
    = link_to 'Események', admin_events_path
  .row
    = link_to 'Borok', admin_wines_path
  .row
    = link_to 'Elérhetőségek', admin_availabilities_path

app/views/admin/availabilities/_form.html.slim
.container
  = form_for [:admin, @availability] do |f|
    - if @availability.errors.any?
      #error_explanation
        h2 = "#{pluralize(@availability.errors.count, "error")} prohibited this availability from being saved:"
        ul
          - @availability.errors.full_messages.each do |message|
            li = message

    .field.form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .field.form-group
      = f.label :url
      = f.text_field :url, class: 'form-control'
      span{style='color: red;'} Mindig http:// vagy https:// kezdetű legyen
    .actions.form-group
      = f.submit

app/views/admin/availabilities/edit.html.slim
h1 Editing availability

== render 'form'

= link_to 'Show', admin_availability_path(@availability)
'|
= link_to 'Back', admin_availabilities_path

app/views/admin/availabilities/index.html.slim
h1 Listing availabilities

table.table.table-hover
  thead
    tr
      th Name
      th Url
      th
      th
      th

  tbody
    - @availabilities.each do |availability|
      tr
        td = availability.name
        td = availability.url
        td = link_to 'Show', admin_availability_path(availability)
        td = link_to 'Edit', edit_admin_availability_path(availability)
        td = link_to 'Destroy', admin_availability_path(availability), data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Availability', new_admin_availability_path
= ' | '
= link_to 'Admin', admin_root_path

app/views/admin/availabilities/new.html.slim
h1 New availability

== render 'form'

= link_to 'Back', admin_availabilities_path

app/views/admin/availabilities/show.html.slim
.container
  .panel.panel-default
    .panel-heading
      .panel-title Name
    .panel-body
      = @availability.name
  .panel.panel-default
    .panel-heading
      .panel-title Url
    .panel-body
      = @availability.url

  = link_to 'Edit', edit_admin_availability_path(@availability)
  = ' | '
  = link_to 'Back', admin_availabilities_path

app/views/admin/events/edit.html.slim
h1 Editing event

== render 'form'

= link_to 'Show', admin_event_path(@event)
'|
= link_to 'Back', admin_events_path

app/views/admin/events/index.html.slim
h1 Listing events

table.table.table-hover
  thead
    tr
      th
      th Name
      th Date and location
      th Url
      th Category
      th
      th
      th

  tbody
    - @events.each do |event|
      tr
        td = image_tag event.image, style: 'max-width: 100px;'
        td = event.name
        td = event.date_and_location
        td = link_to 'link', event.url
        td = event.category
        td = link_to 'Show', admin_event_path(event)
        td = link_to 'Edit', edit_admin_event_path(event)
        td = link_to 'Destroy', admin_event_path(event), data: {:confirm => 'Are you sure?'}, method: :delete

br

= link_to 'New Event', new_admin_event_path
= ' | '
= link_to 'Admin', admin_root_path

app/views/admin/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', admin_events_path

app/views/admin/events/show.html.slim
.container
  .panel.panel-default
    .panel-body
      = image_tag @event.image + '-/resize/100x/'
  .panel.panel-default
    .panel-heading
      .panel-title Name:
    .panel-body
      =@event.name
      br
      =@event.name_eng
  .panel.panel-default
    .panel-heading
      .panel-title Date and location:
    .panel-body
      =@event.date_and_location
      br
      =@event.date_and_location_eng
  .panel.panel-default
    .panel-heading
      .panel-title Start date:
    .panel-body
      =@event.start_date
  .panel.panel-default
    .panel-heading
      .panel-title Url text:
    .panel-body
      =@event.url_text
  .panel.panel-default
    .panel-heading
      .panel-title Url:
    .panel-body
      =@event.url
  .panel.panel-default
    .panel-heading
      .panel-title Category:
    .panel-body
      =@event.category

  = link_to 'Edit', edit_admin_event_path(@event)
  = ' | '
  = link_to 'Back', admin_events_path

app/views/admin/wines/edit.html.slim
h1 Editing wine

== render 'form'

= link_to 'Show', admin_wine_path(@wine)
'|
= link_to 'Back', admin_wines_path

app/views/admin/wines/index.html.slim
h1 Listing wines

table.table.table-hover
  thead
    tr
      th
      th Kind
      th Name
      th Year
      th Category
      th Position
      th
      th
      th

  tbody
    - @wines.each do |wine|
      tr
        td = image_tag wine.image + '-/resize/100x/'
        td = wine.kind
        td = wine.name
        td = wine.year
        td = wine.category
        td = wine.position
        td = link_to 'Show', admin_wine_path(wine)
        td = link_to 'Edit', edit_admin_wine_path(wine)
        td = link_to 'Destroy', admin_wine_path(wine), data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Wine', new_admin_wine_path
= ' | '
= link_to 'Admin', admin_root_path

app/views/admin/wines/new.html.slim
h1 New wine

== render 'form'

= link_to 'Back', admin_wines_path

app/views/admin/wines/show.html.slim
.container
  .panel.panel-default
    = image_tag @wine.image + '-/resize/100x/'
  .panel.panel-default
    .panel-heading
      .panel-title Kind:
    .panel-body
      = @wine.kind
      = @wine.kind_eng
  .panel.panel-default
    .panel-heading
      .panel-title Alcohol:
    .panel-body
      = @wine.alcohol
  .panel.panel-default
    .panel-heading
      .panel-title Name:
    .panel-body
      = @wine.name
      br
      = @wine.name_eng
  .panel.panel-default
    .panel-heading
      .panel-title Year:
    .panel-body
      = @wine.year
  .panel.panel-default
    .panel-heading
      .panel-title Description:
    .panel-body
      = @wine.description
      br
      = @wine.description_eng
  .panel.panel-default
    .panel-heading
      .panel-title Category:
    .panel-body
      = @wine.category
  .panel.panel-default
    .panel-heading
      .panel-title Position:
    .panel-body
      = @wine.position

  = link_to 'Edit', edit_admin_wine_path(@wine)
  '|
  = link_to 'Back', admin_wines_path

app/views/availabilities/_hungarian.html.slim
.container
  .row
    - Availability.all.order(name: :asc).each_with_index do |avaibility|
      .col-md-3.col-sm-4.col-xs-6.block
        .name = avaibility.name
        .url = link_to avaibility.url, avaibility.url
        .line

app/views/pages/eng.html.slim
= render 'popup_eng'
= render 'age_check_eng'

nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .container-fluid#mobile-menu
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .language
        =link_to 'hun', root_path
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'Winery', '#wineries'
        li
          = link_to 'Cellar', '#winery'
        li
          =link_to 'Wines', '#our-wines'
        li
          =link_to 'Wine tasting', '#wine-tasting'
        li
          =link_to 'Events', '#events'
        li
          = link_to 'Shops', '#shop'
        li
          =link_to 'Contact', '#contact'

section.menu#eng
  .container#menu.nopadding
    ul
      li
        = link_to 'Winery', '#wineries'
      li
        = link_to 'Cellar', '#winery'
      li
        =link_to 'Wines', '#our-wines'
      li
        =link_to 'Wine tasting', '#wine-tasting'
      li
        =link_to 'Events', '#events'
      li
        = link_to 'Shops', '#shop'
      li
        =link_to 'Contact', '#contact'
      li.language
        =link_to 'hun', root_path
        span
          | /
        =link_to 'eng', 'javascript:void(0)'
section.slider
  .container.nopadding
    #carousel-example-generic.carousel.slide data-ride="carousel"
      .carousel-inner role="listbox"
        .item.active
          .black-mask
          = image_tag "slider_1.png"
        .item
          .black-mask
          = image_tag "slider_2.png"
        .item
          .black-mask
          = image_tag "slider_3.png"
      a.left.carousel-control data-slide="prev" href="#carousel-example-generic" role="button"
        = image_tag "left_arrow.png"
        span.sr-only Previous
      a.right.carousel-control data-slide="next" href="#carousel-example-generic" role="button"
        = image_tag "right_arrow.png"
        span.sr-only Next
    .slider-logo
      = image_tag "bp_logo.png"
    .contact-row
      = mail_to 'info@dubicz.hu', 'Send us an email', target:'_blank'
      span
        = ' '
        | or
        = ' '
      = link_to 'Follow us', 'https://www.facebook.com/dubicz.hu', target:'_blank'
section.wineries#wineries
  .container.nopadding
    .grey-row
      = image_tag "bp_brown.png"
      .grey-line
    h2 Winery
    article#block-1.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "img_icon.png"
      .text-box
        p DUBICZ
        span
          | /
        p Gyöngyös
        h3 Mátra wine region
        p Where the sun meets the mountain...
    article#block-2.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "wine_icon.png"
      .text-box
        p Fríz Hárslevelű
        span
          | /
        p 2008
        h3 Fríz Hárslevelű
        p Late harvested
    article#block-3.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "eye_icon.png"
      .text-box
        p Winery
        span
          | /
        p Anno  1906
        h3 100 years old cellar system
        p We opened a new era...
    article#block-4.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "pencil_icon.png"
      .text-box.box-centered
        = image_tag "dunai.png"
        h3 Ágnes Dunai
        span Manager
        p Captivated by the world of wines...
        = image_tag "quote_icon.png"
    article#block-5.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "wine_icon.png"
      .text-box
        p The premium wines of our winery
        span
          | /
        p 2014
        h3 1014 series

    article#block-6.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "eye_icon.png"
      .text-box
        p DUBICZ
        span
          | /
        p Gyöngyös
        h3 wine+ tastings
        p
          | (Time) travel to the world of wine...
    article#block-7.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "img_icon.png"
      .text-box
        p DUBICZ
        span
          | /
        p Gyöngyös
        h3 123 hectares of vineyards
        p Tradition and technology
    article#block-8.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "tour_icon.png"
      .text-box
        p DUBICZ
        span
          | /
        p Gyöngyös
        h3
          | Since 1906
          br
          |
        p The gate of Mátra
    article#block-9.col-xs-12.col-sm-6.col-lg-4.nopadding
      .masked
      = image_tag "glasses_icon.png"
      .text-box
        p Contact
        span
          | /
        p Reservation
        h3 be our guest
        p We are waiting for you in our cellar renovated!
section.winery#winery
  .container.nopadding
    .grey-row.white-row
      = image_tag "bp_brown.png"
      .grey-line
    h2 Cellar
    .winery-row
      h3
        | 100 YEARS
        br
        span OF WINE WORLD
    .first-row#boraszat
      .text-box
        h3 WINERY
        .brown-line
        h4 Gyöngyös
        .brown-line
        p Borpalota is located in the inner city of Gyöngyös, in the Mátra wine region. The winery with 100 years of history got renewed in 2014. A new era has started: our aim is to become a major winery of the region again, that is worthy of our name and the founders’ heritage; making wines that show the region’s quality, its freshness and dynamics.
        p Borpalota currently has 123 hectares of vineyards, growing traditional local grapes like Pinot Gris and Muscat Lunel as well as popular international types like Sauvignon Blanc and Cabernet. In the recent years most vineyards have been newly planted, currently we grow a variety of over 10 grapes. In 2014, our winemaking technology got modernised using the latest inventions, thus grew up to our 100-year old cellar system. Besides the terroir of our vineyards, this is the other key factor for producing our wines in consistently high quality.
      .image-box
    .second-row
      .image-box
      .text-box
        .brown-line
        h4 Building
        .brown-line
        p The Borpalota building has been built by the association of local winemakers, founded in 1900. The cellar system was used for winemaking and gave the foundation for the office building. The inauguration took place in 1907, and, despite all turbulences of the 20th century, the building remained a vinery ever since. The companies located here have always played a major role in the life of Mátra vine region.
        .brown-line
        h4 Cellar
        .brown-line
        p In our renewed wine cellar, visitors can take part in a wonderful time-traveling to the world of wines. Our guests can walk around in the nearly 1 km long cellar, where they can get acquainted with the winery’s 110 years of history. Our visitors can see the 6000-litre wooden casks used 100 years ago as well as concrete barrels from 30 to 80 000 litres built in the 1960’s, together with the 21st century’s modern technology of steel barrels.
section.our-wines#our-wines
  .container.nopadding
    .white-row
      = image_tag "wine_glass.png"
      .grey-line
    h2 Wines
    .series-row#thousand-fourteen
      .series.col-xs-12.col-md-6
        h3
          span 1014&nbsp;
          | series
        p The premium wines of our winery belong to the “1014” family – the name refers to the height of Kékes, the local mountain’s peak, which is the highest point of Hungary. We produce only our best wines under this label, the ones we are the mostly proud of.
        p Their style includes a little fermentation in wooden cascs, which makes these wines more complex; however, we consider this as a supporting act that should not dominate our wines.
      .series.nopadding.col-xs-12.col-md-6
        = image_tag "1014_head.png"
      = render 'wines/english', wine_category: '1014 sorozat'
    .series-row#borpalota
      .series.col-xs-12.col-md-6
        h3
          span HIKER&nbsp;
          | series
        p Basic product line can be the favorite for walkers, hikers. In the label there you can find Matra rocks, trees marks with hiker-signs. Excellent value wines contains in this category. These are fresh, reductive and full of fragrant and fruits.
      .series.nopadding.col-xs-12.col-md-6
        = image_tag "bp_head.png"
      = render 'wines/english', wine_category: 'Túrajeles sorozat'
    .series-row#wine-speciality
      .series.col-xs-12.col-md-6
        h3
          span Special wines
      .series.nopadding.col-xs-12.col-md-6
        = image_tag "speciality_head.png"
      = render 'wines/english', wine_category: 'Borkülönlegességek'
section.wine-tasting#wine-tasting
  .container.nopadding
    .grey-row.white-row
      = image_tag "bp_brown.png"
      .grey-line
    h2 Commercialisation
    .tasting-row
      h3
        | TIME TRAVEL
        br
        span TO THE WORLD OF WINE
    .first-row
      .image-box
      .text-box
        h3 Wine tasting
        p Our wine tasting room can serve up to 50 persons. If requested in advance, we gladly arrange snacks, cold platters or even hot meals to complete the wine tasting experience. The meals are prepared by the famous local restaurant, Kékes Restaurant.
        p Our wines are presented every time by an expert, and all our products can be bought locally. The prices of the wine tastings include mineral water and snacks.
    .second-row#csomagjaink
      .text-box
        h3 Our wine tasting offers:
        .brown-line
        ul
          li
            | 5 wines
            span 1750.- HUF/person
          li
            | 6 wines
            span 2000.- HUF/person
          li
            | 7 wines
            span 2250.- HUF/person
          li
            | 8 wines
            span 2500.- HUF/person
          li
            | 10 wines
            span 3000.- HUF/person
          li
          li
            | Cakes (15 dkg)
            span 300.- HUF/person
          li
            | Cheeses (15 dkg)
            span 500.- HUF/person
        .brown-line
        p Hot meals, lunch and dinner according to restaurant’s offer based on requests.
        p Our prices do not include VAT.
        p After wine tasting our guests have the opportunity to purchase from the winery’s vines.
        p Wine tasting room can be rented for special events; live music can be arranged if necessary.
      .image-box

section.events#events
  .container.nopadding
    .grey-row.white-row
      = image_tag "glasses_brown.png"
      .grey-line
    h2 Events
    p.subtitle
      | For offers, news and actualities please visit our
      = ' '
      = link_to 'Facebook', 'https://www.facebook.com/dubicz.hu'
      |  site.
    .event-row.nopadding#wine-tastings
      .event.col-xs-12.col-md-6
        h3 Topicality
      = render 'events/english', event_category: 'Aktualitások'
    .event-row#festivals
      .masked
      .event.col-xs-12.col-md-6
        h3 Events
      = render 'events/english', event_category: 'Események'

section.availabilities#shop
  .container.nopadding
    .white-row
      .grey-line
    h2 Shops
    .content
      = render 'availabilities/hungarian'

section.contact#contact
  .container.nopadding
    .white-row
      .grey-line
    h2 Contact
    .map
      .mask
        .content
          h3 Contact Us
          .left-column.nopadding.col-xs-12.col-md-7
            p Company: Dubicz Winery and Vineyards
            = link_to 'Address: H-3200 Gyöngyös, Koháry út 4.', 'https://www.google.hu/maps/place/Borpalota+Bor%C3%A1szat+%C3%A9s+Sz%C5%91l%C5%91birtok/@47.7838986,19.9308844,17z/data=!3m1!4b1!4m2!3m1!1s0x47405a1acbfa89c1:0x7370c139fa16a8a4', class: 'google-map', target:'_blank'
            ul
              li
                | Telephone: +36
                span
                  |/
                | 37
                span
                  |/
                | 301
                span
                  |/
                | 015
              li
                | Fax: +36
                span
                  |/
                | 37
                span
                  |/
                | 301
                span
                  |/
                | 693
              li
                | Email:
                = mail_to ' info@dubicz.hu'
              li
                | Web:
                = link_to 'www.dubicz.hu', 'http://www.dubicz.hu/'
            = link_to 'For offers, news and actualities please visit our Facebook site.', 'https://www.facebook.com/dubicz.hu', class: 'facebook', target:'_blank'

          .right-column.nopadding.col-xs-12.col-md-5
            p Send a message to us!
            = form_for :message, url: pages_send_email_path, method: :post, remote: true, html: { id: "form" } do |f|
              .name
                label for="name"
                = f.text_field :name, id: 'name', placeholder: "Name"
              .email
                label for="email"
                = f.email_field :email, id: 'email', placeholder: "Email"
              .message
                label for="message"
                = f.text_area :message, id: 'message', placeholder: "Message"
              .subject
                label for="subject"
                = f.text_field :subject, id: 'subject'
              .submit
                = f.submit "Send", id: 'submit'

section
  .container.nopadding
    .footer
      = image_tag "logo_footer.png"
      .divider
      //= link_to 'ADATVÉDELMI NYILATKOZAT', '#'
      //= link_to 'VÁSÁRLÁSI ÉS SZÁLLÍTÁSI FELTÉTELEK', '#'
      //= link_to 'KAPCSOLAT', '#'
      p
        | DESIGN BY
        = ' '
        span ANDRÁS BERECZ DESIGN / 2015
      p
        | DEVELOPED BY
        = ' '
        = link_to 'APP MAINTAINERS LTD', 'http://www.appmaintainers.com/', class: 'appmaintainers', target:'_blank'

app/views/user_message/user_message.html.erb
<%= @name %>
<%= @email %>
<%= @message %>